fedora:
	g++ main.cpp shader.cpp text2D.cpp helper.cpp Character.hpp texture.cpp Collision.hpp GLSL.cpp *.cc -lGL -lGLEW -lglfw -std=c++11

osx:
	clang++ -std=c++11 -stdlib=libc++ *.cpp *.cc -lglfw3 -framework OpenGL -lGLEW
